[package]
name = "cxs-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
cxs-core = { path = "../cxs-core" }
cxs-mux = { path = "../cxs-mux" }
futures-util.workspace = true
serde_json.workspace = true
subtle.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[lints]
workspace = true
